services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    volumes:
      - ./app:/app/app      # Mount the code
      - ./data/chroma_db:/app/data/chroma_db
      - ./pdfs:/app/pdfs
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_MODEL=${OPENROUTER_MODEL}
      - REDIS_URL=${REDIS_URL}
      - WEB_SEARCH_PROVIDER=${WEB_SEARCH_PROVIDER}
      - CHROMA_TELEMETRY_DISABLED=1
    ports:
      - "8000:8000"
    depends_on:
      - redis
  redis:
    image: "redis:7"
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
